[project]
name = "myPyllant"
authors = [
  { name="Philipp", email="pd@signalkraft.com" },
]
description = "A Python library to interact with the API behind the myVAILLANT app"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "aiohttp>=3.8.0",
  "pydantic>=1.10.0",
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/signalkraft/myPyllant"
"Bug Tracker" = "https://github.com/signalkraft/myPyllant/issues"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = "--cov=src"
asyncio_mode = "auto"
testpaths = [
    "tests",
]